version: 0.2
#env:
 # variables:
  #  AWS_DEFAULT_REGION: "us-west-2"
phases:
  install:
    commands:
      - apt-get -y update
        # - apt-get -y install jq
  pre_build:
      commands:

      # load acs submodule (since codebuild doesn't pull the .git folder from the repo
      # - cd common 
      # - git clone https://github.com/nikhitanikhilesh/learn-terraform-code-organization.git
      #  - cd ../

      #install terraform
         - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
         - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
         - sudo apt-get update && sudo apt-get install terraform
         - terraform -help  
         - terraform --version

      #set env variables for terraform provider
      #  - curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq 'to_entries | [ .[] | select(.key | (contains("Expiration") or contains("RoleArn"))  | not) ] |  map(if .key == "AccessKeyId" then . + {"key":"AWS_ACCESS_KEY_ID"} else . end) | map(if .key == "SecretAccessKey" then . + {"key":"AWS_SECRET_ACCESS_KEY"} else . end) | map(if .key == "Token" then . + {"key":"AWS_SESSION_TOKEN"} else . end) | map("export \(.key)=\(.value)") | .[]' -r > /tmp/cred.txt # work around https://github.com/hashicorp/terraform/issues/8746
        # - chmod +x /tmp/cred.txt
        #     - . /tmp/cred.txt
  build:
    commands:
      - git clone https://github.com/nikhitanikhilesh/learn-terraform-code-organization.git      
      - ls
      - cd learn-terraform-code-organization 
      - terraform init 
      - terraform plan 
      - terraform apply
